-- supabase/migrations/20250406204100_create_scribes_table.sql

-- Create the scribes table
create table public.scribes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  content text null -- Storing the generated scribe text
);

-- Enable Row Level Security (RLS) - Recommended for security
alter table public.scribes enable row level security;

-- Create basic policies for RLS.
-- For now, allow any authenticated user to insert and read all scribes.
-- You might want to refine these later, e.g., by adding a user_id column
-- to associate scribes with specific users.

create policy "Allow authenticated insert access"
on public.scribes
for insert to authenticated with check (true);

create policy "Allow authenticated read access"
on public.scribes
for select to authenticated using (true);

-- Add an index on created_at for faster sorting/filtering
create index idx_scribes_created_at on public.scribes (created_at desc);
